### ISSUE TITLE
Implement model & instance level `update` methods.

### ISSUE THREAD

**Issue by thedodd** [thedodd/wither#5]
`Model.save` is good. Works as needed, but `update` is needed for atomic operations so that concurrent updates to a document do not result in data loss or data races.

**Comment by SamuelMarks** [comment]
Great idea!

**Comment by thedodd** [comment]
Should be able to knock this out tomorrow.

**Comment by thedodd** [comment]
@SamuelMarks as you are the only other person to have commented on this thread, you are welcome to take a gander at https://github.com/thedodd/wither/pull/6 for some quick feedback. Else, I will go ahead and make this available as `0.4.0` tomorrow.

**Comment by SamuelMarks** [comment]
Looks good!
