### ISSUE TITLE
Model: failed to parse serde rename attr

### ISSUE THREAD

**Issue by losintikfos** [thedodd/wither#50]
I am trying to experiment with branch [42-new-driver](https://github.com/thedodd/wither/tree/42-new-driver) with the model below.

```
use bson::oid::ObjectId;
use serde::{Deserialize, Serialize};
use wither::Model;

#[derive(Serialize, Deserialize, Model)]
struct Foo {
    #[serde(rename = "_id", skip_serializing_if = "Option::is_some")]
    id: Option<ObjectId>,
}
```
The `serde(rename...`  annotation generated this error:

> 
> failed to parse serde rename attr
> 
> help: Unexpected literal type `string`rustc
...

The error disappear when I remove `Model` from derive -- do you know why this is happening?

**Comment by thedodd** [comment]
Oh man. Yea, there is a lot of stuff that is unstable on that branch right now ... I have another large changeset coming in on that branch very soon (I've been hacking on it over the last few days).

**Comment by thedodd** [comment]
It is definitely not ready for use right now.
