### ISSUE TITLE
Support delete_many 

### ISSUE THREAD

**Issue by ndelvalle** [thedodd/wither#67]
First of all, thanks for the lib, I am testing it in a new project and so far I like it!
I came across the use case of deleting many attributes, are there any plans to support [delete_many](https://docs.rs/mongodb/1.1.1/mongodb/struct.Collection.html#method.delete_many) functionality or should I just use the native drive for this case?

**Comment by thedodd** [comment]
Hey @ndelvalle, glad that you like it so far! Looks like that is actually just missing functionality. We should definitely have that functionality.

You can currently do this by simple calling `Model::collection(&db).delete_many(..).await`. When we implement this functionality in Wither, it will do the exact same thing.

**Comment by thedodd** [comment]
If you have time to open a PR, it should be quite simple. Feel free to do so.

**Comment by ndelvalle** [comment]
@thedodd yeah that is what I am currently doing.

> If you have time to open a PR, it should be quite simple. Feel free to do so.

Sure I'll try to make a PR 💪🏻

**Comment by thedodd** [comment]
Closed by #68 
Closed by #72
