### ISSUE TITLE
Mongo Rust driver upgrade coming

### ISSUE THREAD

**Issue by c650** [thedodd/wither#69]
Hey there, we are going to see a new version of https://github.com/mongodb/mongo-rust-driver soon along with the upgrade to MongoDB 4.4 (up from 4.2) on Atlas.

**Comment by thedodd** [comment]
@c650 awesome, thanks for the heads-up.

**Comment by simoneromano96** [comment]
It should be a simple version bump, I'm locally trying the alpha version and for now I'm not having any issue

**Comment by c650** [comment]
Great!!!

**Comment by thedodd** [comment]
@c650 in reviewing the way we depend on the mongodb crate (https://github.com/thedodd/wither/blob/master/wither/Cargo.toml#L18) it looks like we will not actually need to update anything. As long as the update is still part of the `1.x` line, then things will continue to work with Wither. Is there something more complex which I am missing?

**Comment by c650** [comment]
@thedodd i dont think so. i just got an email from mongo atlas saying to make sure to update drivers. should be fine to close and if anything breaks ill let you know. thanks for making this lib i <3 it

**Comment by thedodd** [comment]
Sounds great! Thank you!
