### ISSUE TITLE
Nice way to collect a cursor?

### ISSUE THREAD

**Issue by wbrickner** [thedodd/wither#77]
Hello, it's me again 🤪.

What I've been doing to fetch many matching documents is I use the `::find` method and then collect those one at a time manually, and I would suspect there's a cleaner way built in to wither.

![collect_cursor](https://user-images.githubusercontent.com/2095902/111053898-71a58600-842d-11eb-8672-b91ae4027dbf.png)

Is this at least correct? I may be mishandling the stream of `Option<Result<Model, WitherError>>`.

**Comment by thedodd** [comment]
Hey there. A few things to keep in mind:
- The `ModelCursor` is a stream but is ALSO a [TryStream](https://docs.rs/futures/0.3.13/futures/stream/trait.TryStream.html) — which is true for any stream yielding `Result`s.
- As such, we have access to the `TryStreamExt` (as long as you bring it into scope), which means you have access to [`TryStreamExt::try_collect`](https://docs.rs/futures/0.3.13/futures/stream/trait.TryStreamExt.html#method.try_collect).

That said, all of the work is taken care of and we get the added bonus of easy error handling. So your above code could be refined down to:

```rust
use futures::prelude::*;
let cursor = Model::find(&db, filter, opts).await?;
let models: Vec<_> = cursor.try_collect().await?; // Gives you a `Vec<M>` just like your image above.
```

This will propagate an error if creating the cursor fails, but will also propagate an error if an error takes place while streaming over the cursor. The propagated error type in this case will always be a `WitherError`.

**Comment by wbrickner** [comment]
That is nicer, thank you!
